version: "3.8"

services:
  flume:
    build: ./docker/
    volumes: 
     - ./volume-dir:/home/
    ports:
      - 9100:50070
      - 9106:50075
      - 9101:8088
      - 9102:8080 
      - 9103:8042 
      - 9104:8081 
      - 9105:19888 
    #command: /opt/flume/bin/flume-ng agent -n agent -c conf -f /home/hadoop.conf -Dflume.root.logger=INFO,console #tail -f /dev/null