version: "3.8"

services:
  flume2:
    build: ./docker/
    volumes: 
     - ./volume-dir:/home/
    ports:
      - 8100:50070
      - 8106:50075
      - 8101:8088
      - 8102:8080 
      - 8103:8042 
      - 8104:8081 
      - 8105:19888 
    command: /opt/flume/bin/flume-ng agent -n agent -c conf -f /home/hadoop.conf -Dflume.root.logger=INFO,console #tail -f /dev/null